name: NCLT Matter Watch

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'    # 09:00 IST
    - cron: '30 11 * * *'   # 17:00 IST
    - cron: '30 12 * * *'   # 18:00 IST
    - cron: '30 13 * * *'   # 19:00 IST
